/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SpawnProcess */

#ifndef _Included_SpawnProcess
#define _Included_SpawnProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SpawnProcess
 * Method:    exec
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;)LProcess;
 */
JNIEXPORT jobject JNICALL Java_SpawnProcess_exec
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
