/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class runutils_SpawnProcess */

#ifndef _Included_runutils_SpawnProcess
#define _Included_runutils_SpawnProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     runutils_SpawnProcess
 * Method:    exec_process
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;)Lrunutils/SpawnProcess/SpawnedProcess;
 */
JNIEXPORT jobject JNICALL Java_runutils_SpawnProcess_exec_1process
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

/*
 * Class:     runutils_SpawnProcess
 * Method:    killProcess
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_runutils_SpawnProcess_killProcess
  (JNIEnv *, jclass, jint);

/*
 * Class:     runutils_SpawnProcess
 * Method:    waitForProcess
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_runutils_SpawnProcess_waitForProcess
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class runutils_SpawnProcess_SpawnedProcess */

#ifndef _Included_runutils_SpawnProcess_SpawnedProcess
#define _Included_runutils_SpawnProcess_SpawnedProcess
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
