/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SpawnProcess */

#ifndef _Included_SpawnProcess
#define _Included_SpawnProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SpawnProcess
 * Method:    exec
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;)LSpawnProcess/SpawnedProcess;
 */
JNIEXPORT jobject JNICALL Java_SpawnProcess_exec
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

/*
 * Class:     SpawnProcess
 * Method:    killProcess
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SpawnProcess_killProcess
  (JNIEnv *, jclass, jint);

/*
 * Class:     SpawnProcess
 * Method:    waitForProcess
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SpawnProcess_waitForProcess
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class SpawnProcess_SpawnedProcess */

#ifndef _Included_SpawnProcess_SpawnedProcess
#define _Included_SpawnProcess_SpawnedProcess
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
