/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __net_axiak_runutils_SpawnProcess__
#define __net_axiak_runutils_SpawnProcess__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT jobject JNICALL Java_net_axiak_runutils_SpawnProcess_exec_1process (JNIEnv *env, jclass, jobjectArray, jobjectArray, jstring);
JNIEXPORT void JNICALL Java_net_axiak_runutils_SpawnProcess_killProcess (JNIEnv *env, jclass, jint);
JNIEXPORT jint JNICALL Java_net_axiak_runutils_SpawnProcess_waitForProcess (JNIEnv *env, jclass, jint);

#ifdef __cplusplus
}
#endif

#endif /* __net_axiak_runutils_SpawnProcess__ */
